[build]
  Command = "npm run build"
  functions = "netlify-lambda"
  Publish = "public"

[dev]
  command = "yarn start" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server
  targetPort = 3000 # Port of target app server
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser